replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: realrepo/protor
  tag: 1.0
service:
  name: protor-service
  type: ClusterIP
  externalPort: 8080
  internalPort: 80
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
ingress:
  enabled: false
